package com.samsungsds.analyst.code.api;

public enum ProgressEvent {
	PREPARE_COMPLETE, SONAR_START_COMPLETE,
	CODE_SIZE_COMPLETE, DUPLICATION_COMPLETE, COMPLEXITY_COMPLETE,
	SONARJAVA_COMPLETE, JAVASCRIPT_COMPLETE, CSS_COMPLETE, HTML_COMPLETE, SONAR_ALL_COMPLETE,
	PMD_COMPLETE, FINDBUGS_COMPLETE, FINDSECBUGS_COMPLETE,
	DEPENDENCY_COMPLETE, UNUSED_COMPLETE,
	FINAL_COMPLETE
}
